language: node_js
node_js:
- 13
script:
- npm run build 
before_install:
- openssl aes-256-cbc -K $encrypted_2861304911d5_key -iv $encrypted_2861304911d5_iv
  -in travis_deploy_key.enc -out ~/travis_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ~/travis_deploy_key
- echo -e "Host ipsaone.space\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ~/travis_deploy_key
- ssh -i ~/travis_deploy_key travis@ipsaone.space pwd
- ssh -i ~/travis_deploy_key travis@ipsaone.space echo $TRAVIS_BRANCH

after_success:
- ./scripts/deploy.sh
