language: node_js
node_js:
- 12
script:
- npm run build
before_install:
- openssl aes-256-cbc -K $encrypted_2861304911d5_key -iv $encrypted_2861304911d5_iv
  -in travis_deploy_key.enc -out ~/travis_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ~/travis_deploy_key
- echo -e "Host ipsaone.space\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ~/travis_deploy_key
- ssh -i ~/travis_deploy_key travis@ipsaone.space pwd

after_success:
- zip -r ./dist.zip ./dist
- scp -i ~/travis_deploy_key ./dist.zip travis@ipsaone.space:~/dist-deploying.zip
- ssh -i ~/travis_deploy_key travis@ipsaone.space -- unzip ~/dist-deploying.zip -d ~/ANNA-Frontend-prod-new
- ssh -i ~/travis_deploy_key travis@ipsaone.space -- mv ~/ANNA-Frontend-prod ~/ANNA-Frontend-prod-old
- ssh -i ~/travis_deploy_key travis@ipsaone.space -- mv ~/ANNA-Frontend-prod-new ~/ANNA-Frontend-prod
- ssh -i ~/travis_deploy_key travis@ipsaone.space -- rm -rf ~/dist-deploying.zip ~/ANNA-Frontend-prod-old